[Dialog(name='crypto-bot', date=datetime.datetime(2019, 5, 20, 22, 21, 34, tzinfo=datetime.timezone.utc),
        draft= < telethon.tl.custom.draft.Draft object at 0x04790890 >, message = Message(id=1039, to_id=PeerUser(
    user_id=890843151), date=datetime.datetime(2019, 5, 20, 22, 21, 34, tzinfo=datetime.timezone.utc), message='Start',
                                                                                          out=True, mentioned=False,
                                                                                          media_unread=False,
                                                                                          silent=False, post=False,
                                                                                          from_scheduled=False,
                                                                                          from_id=883549834,
                                                                                          fwd_from=None,
                                                                                          via_bot_id=None,
                                                                                          reply_to_msg_id=None,
                                                                                          media=None, reply_markup=None,
                                                                                          entities=[], views=None,
                                                                                          edit_date=None,
                                                                                          post_author=None,
                                                                                          grouped_id=None), entity = User(
    id=890843151, is_self=False, contact=False, mutual_contact=False, deleted=False, bot=True, bot_chat_history=False,
    bot_nochats=False, verified=False, restricted=False, min=False, bot_inline_geo=False, support=False,
    access_hash=-7095899347144758520, first_name='crypto-bot', last_name=None, username='cryptogroupsRev001bot',
    phone=None, photo=None, status=None, bot_info_version=1, restriction_reason=None, bot_inline_placeholder=None,
    lang_code=None)), Dialog(name='TestMaster',
                             date=datetime.datetime(2019, 5, 20, 22, 18, 31, tzinfo=datetime.timezone.utc),
                             draft= < telethon.tl.custom.draft.Draft
object
at
0x04790910 >, message = Message(id=1034, to_id=PeerChat(chat_id=354659824),
                                date=datetime.datetime(2019, 5, 20, 22, 18, 31, tzinfo=datetime.timezone.utc),
                                message='456', out=True, mentioned=False, media_unread=False, silent=False, post=False,
                                from_scheduled=False, from_id=883549834, fwd_from=None, via_bot_id=None,
                                reply_to_msg_id=None, media=None, reply_markup=None, entities=[], views=None,
                                edit_date=None, post_author=None, grouped_id=None), entity = Chat(id=354659824,
                                                                                                  title='TestMaster',
                                                                                                  photo=ChatPhotoEmpty(),
                                                                                                  participants_count=2,
                                                                                                  date=datetime.datetime(
                                                                                                      2019, 5, 4, 16,
                                                                                                      57, 16,
                                                                                                      tzinfo=datetime.timezone.utc),
                                                                                                  version=5,
                                                                                                  creator=True,
                                                                                                  kicked=False,
                                                                                                  left=False,
                                                                                                  deactivated=False,
                                                                                                  migrated_to=None,
                                                                                                  admin_rights=None,
                                                                                                  default_banned_rights=ChatBannedRights(
                                                                                                      until_date=datetime.datetime(
                                                                                                          2038, 1, 19,
                                                                                                          3, 14, 7,
                                                                                                          tzinfo=datetime.timezone.utc),
                                                                                                      view_messages=False,
                                                                                                      send_messages=False,
                                                                                                      send_media=False,
                                                                                                      send_stickers=False,
                                                                                                      send_gifs=False,
                                                                                                      send_games=False,
                                                                                                      send_inline=False,
                                                                                                      embed_links=False,
                                                                                                      send_polls=False,
                                                                                                      change_info=False,
                                                                                                      invite_users=False,
                                                                                                      pin_messages=False))), Dialog(
    name='TestSourceA', date=datetime.datetime(2019, 5, 20, 22, 18, 28, tzinfo=datetime.timezone.utc),
    draft= < telethon.tl.custom.draft.Draft
object
at
0x04790990 >, message = Message(id=1033, to_id=PeerChat(chat_id=395315655),
                                date=datetime.datetime(2019, 5, 20, 22, 18, 28, tzinfo=datetime.timezone.utc),
                                message='123', out=True, mentioned=False, media_unread=False, silent=False, post=False,
                                from_scheduled=False, from_id=883549834, fwd_from=None, via_bot_id=None,
                                reply_to_msg_id=None, media=None, reply_markup=None, entities=[], views=None,
                                edit_date=None, post_author=None, grouped_id=None), entity = Chat(id=395315655,
                                                                                                  title='TestSourceA',
                                                                                                  photo=ChatPhotoEmpty(),
                                                                                                  participants_count=2,
                                                                                                  date=datetime.datetime(
                                                                                                      2019, 5, 8, 15,
                                                                                                      31, 28,
                                                                                                      tzinfo=datetime.timezone.utc),
                                                                                                  version=3,
                                                                                                  creator=True,
                                                                                                  kicked=False,
                                                                                                  left=False,
                                                                                                  deactivated=False,
                                                                                                  migrated_to=None,
                                                                                                  admin_rights=None,
                                                                                                  default_banned_rights=ChatBannedRights(
                                                                                                      until_date=datetime.datetime(
                                                                                                          2038, 1, 19,
                                                                                                          3, 14, 7,
                                                                                                          tzinfo=datetime.timezone.utc),
                                                                                                      view_messages=False,
                                                                                                      send_messages=False,
                                                                                                      send_media=False,
                                                                                                      send_stickers=False,
                                                                                                      send_gifs=False,
                                                                                                      send_games=False,
                                                                                                      send_inline=False,
                                                                                                      embed_links=False,
                                                                                                      send_polls=False,
                                                                                                      change_info=False,
                                                                                                      invite_users=False,
                                                                                                      pin_messages=False))), Dialog(
    name='TestSourceB', date=datetime.datetime(2019, 5, 20, 22, 18, 25, tzinfo=datetime.timezone.utc),
    draft= < telethon.tl.custom.draft.Draft
object
at
0x04790A10 >, message = Message(id=1032, to_id=PeerChat(chat_id=322207387),
                                date=datetime.datetime(2019, 5, 20, 22, 18, 25, tzinfo=datetime.timezone.utc),
                                message='asd', out=True, mentioned=False, media_unread=False, silent=False, post=False,
                                from_scheduled=False, from_id=883549834, fwd_from=None, via_bot_id=None,
                                reply_to_msg_id=None, media=None, reply_markup=None, entities=[], views=None,
                                edit_date=None, post_author=None, grouped_id=None), entity = Chat(id=322207387,
                                                                                                  title='TestSourceB',
                                                                                                  photo=ChatPhotoEmpty(),
                                                                                                  participants_count=2,
                                                                                                  date=datetime.datetime(
                                                                                                      2019, 5, 8, 15,
                                                                                                      31, 38,
                                                                                                      tzinfo=datetime.timezone.utc),
                                                                                                  version=3,
                                                                                                  creator=True,
                                                                                                  kicked=False,
                                                                                                  left=False,
                                                                                                  deactivated=False,
                                                                                                  migrated_to=None,
                                                                                                  admin_rights=None,
                                                                                                  default_banned_rights=ChatBannedRights(
                                                                                                      until_date=datetime.datetime(
                                                                                                          2038, 1, 19,
                                                                                                          3, 14, 7,
                                                                                                          tzinfo=datetime.timezone.utc),
                                                                                                      view_messages=False,
                                                                                                      send_messages=False,
                                                                                                      send_media=False,
                                                                                                      send_stickers=False,
                                                                                                      send_gifs=False,
                                                                                                      send_games=False,
                                                                                                      send_inline=False,
                                                                                                      embed_links=False,
                                                                                                      send_polls=False,
                                                                                                      change_info=False,
                                                                                                      invite_users=False,
                                                                                                      pin_messages=False))), Dialog(
    name='testingbot', date=datetime.datetime(2019, 5, 4, 15, 13, 18, tzinfo=datetime.timezone.utc),
    draft= < telethon.tl.custom.draft.Draft
object
at
0x04790A90 >, message = Message(id=67, to_id=PeerUser(user_id=883549834),
                                date=datetime.datetime(2019, 5, 4, 15, 13, 18, tzinfo=datetime.timezone.utc),
                                message='', out=False, mentioned=False, media_unread=False, silent=False, post=False,
                                from_scheduled=False, from_id=768133708, fwd_from=None, via_bot_id=None,
                                reply_to_msg_id=None, media=MessageMediaDocument(
        document=Document(id=5075709315810067039, access_hash=-2202616259120906268,
                          file_reference=b'\x01\x00\x00\x00C\\\xe3(n\xcb\xb0\x006\xad\xaa\xbe\x90\xa2\x1f\xd2)\xbc\x90\x12\x86',
                          date=datetime.datetime(2019, 5, 4, 15, 13, 17, tzinfo=datetime.timezone.utc),
                          mime_type='text/csv', size=2755, dc_id=1,
                          attributes=[DocumentAttributeFilename(file_name='tweets_file.csv')], thumbs=[]),
        ttl_seconds=None), reply_markup=None, entities=[], views=None, edit_date=None, post_author=None,
                                grouped_id=None), entity = User(id=768133708, is_self=False, contact=False,
                                                                mutual_contact=False, deleted=False, bot=True,
                                                                bot_chat_history=False, bot_nochats=False,
                                                                verified=False, restricted=False, min=False,
                                                                bot_inline_geo=False, support=False,
                                                                access_hash=-5688974066162208351,
                                                                first_name='testingbot', last_name=None,
                                                                username='pruebatestbot', phone=None, photo=None,
                                                                status=None, bot_info_version=1,
                                                                restriction_reason=None, bot_inline_placeholder=None,
                                                                lang_code=None)), Dialog(name='Telegram',
                                                                                         date=datetime.datetime(2019, 4,
                                                                                                                26, 15,
                                                                                                                28, 11,
                                                                                                                tzinfo=datetime.timezone.utc),
                                                                                         draft= < telethon.tl.custom.draft.Draft
object
at
0x04790B30 >, message = Message(id=32, to_id=PeerUser(user_id=883549834),
                                date=datetime.datetime(2019, 4, 26, 15, 28, 11, tzinfo=datetime.timezone.utc),
                                message='Código de inicio de sesión: 15185. No entregues este código a nadie, ¡aunque te digan que son parte de Telegram!\n\nEste código puede ser utilizado para iniciar sesión en tu cuenta de Telegram. Nunca lo pedimos para otras cosas.\n\nSi no solicitaste este código al intentar iniciar la sesión en otro dispositivo, simplemente ignora este mensaje.',
                                out=False, mentioned=False, media_unread=False, silent=False, post=False,
                                from_scheduled=False, from_id=777000, fwd_from=None, via_bot_id=None,
                                reply_to_msg_id=None, media=None, reply_markup=None,
                                entities=[MessageEntityBold(offset=0, length=27),
                                          MessageEntityBold(offset=35, length=2)], views=None, edit_date=None,
                                post_author=None, grouped_id=None), entity = User(id=777000, is_self=False,
                                                                                  contact=False, mutual_contact=False,
                                                                                  deleted=False, bot=False,
                                                                                  bot_chat_history=False,
                                                                                  bot_nochats=False, verified=True,
                                                                                  restricted=False, min=False,
                                                                                  bot_inline_geo=False, support=True,
                                                                                  access_hash=2920152423982837246,
                                                                                  first_name='Telegram', last_name=None,
                                                                                  username=None, phone='42777',
                                                                                  photo=UserProfilePhoto(
                                                                                      photo_id=3337190045231018,
                                                                                      photo_small=FileLocationToBeDeprecated(
                                                                                          volume_id=702229962,
                                                                                          local_id=26779),
                                                                                      photo_big=FileLocationToBeDeprecated(
                                                                                          volume_id=702229962,
                                                                                          local_id=26781), dc_id=1),
                                                                                  status=UserStatusOffline(
                                                                                      was_online=datetime.datetime(2017,
                                                                                                                   5,
                                                                                                                   22,
                                                                                                                   22,
                                                                                                                   53,
                                                                                                                   9,
                                                                                                                   tzinfo=datetime.timezone.utc)),
                                                                                  bot_info_version=None,
                                                                                  restriction_reason=None,
                                                                                  bot_inline_placeholder=None,
                                                                                  lang_code=None)), Dialog(
    name='Mela💕', date=datetime.datetime(2019, 4, 26, 15, 17, 28, tzinfo=datetime.timezone.utc),
    draft= < telethon.tl.custom.draft.Draft
object
at
0x04790BB0 >, message = Message(id=30, to_id=PeerUser(user_id=888583501),
                                date=datetime.datetime(2019, 4, 26, 15, 17, 28, tzinfo=datetime.timezone.utc),
                                message='test', out=True, mentioned=False, media_unread=False, silent=False, post=False,
                                from_scheduled=False, from_id=883549834, fwd_from=None, via_bot_id=None,
                                reply_to_msg_id=None, media=None, reply_markup=None, entities=[], views=None,
                                edit_date=None, post_author=None, grouped_id=None), entity = User(id=888583501,
                                                                                                  is_self=False,
                                                                                                  contact=True,
                                                                                                  mutual_contact=True,
                                                                                                  deleted=False,
                                                                                                  bot=False,
                                                                                                  bot_chat_history=False,
                                                                                                  bot_nochats=False,
                                                                                                  verified=False,
                                                                                                  restricted=False,
                                                                                                  min=False,
                                                                                                  bot_inline_geo=False,
                                                                                                  support=False,
                                                                                                  access_hash=-2305153242132437762,
                                                                                                  first_name='Mela💕',
                                                                                                  last_name=None,
                                                                                                  username=None,
                                                                                                  phone='50672437675',
                                                                                                  photo=None,
                                                                                                  status=UserStatusOffline(
                                                                                                      was_online=datetime.datetime(
                                                                                                          2019, 4, 17,
                                                                                                          3, 28, 54,
                                                                                                          tzinfo=datetime.timezone.utc)),
                                                                                                  bot_info_version=None,
                                                                                                  restriction_reason=None,
                                                                                                  bot_inline_placeholder=None,
                                                                                                  lang_code=None)), Dialog(
    name='BotFather', date=datetime.datetime(2019, 4, 25, 23, 17, 35, tzinfo=datetime.timezone.utc),
    draft= < telethon.tl.custom.draft.Draft
object
at
0x04790C30 >, message = Message(id=29, to_id=PeerUser(user_id=883549834),
                                date=datetime.datetime(2019, 4, 25, 23, 17, 35, tzinfo=datetime.timezone.utc),
                                message="Done! Congratulations on your new bot. You will find it at t.me/cryptogroupsRev001bot. You can now add a description, about section and profile picture for your bot, see /help for a list of commands. By the way, when you've finished creating your cool bot, ping our Bot Support if you want a better username for it. Just make sure the bot is fully operational before you do this.\n\nUse this token to access the HTTP API:\n890843151:AAE43ZXhsgy08CeWgbhb5l5zRjI85-XMlug\nKeep your token secure and store it safely, it can be used by anyone to control your bot.\n\nFor a description of the Bot API, see this page: https://core.telegram.org/bots/api",
                                out=False, mentioned=False, media_unread=False, silent=False, post=False,
                                from_scheduled=False, from_id=93372553, fwd_from=None, via_bot_id=None,
                                reply_to_msg_id=None, media=None, reply_markup=ReplyKeyboardHide(selective=False),
                                entities=[MessageEntityUrl(offset=59, length=26),
                                          MessageEntityBotCommand(offset=170, length=5),
                                          MessageEntityCode(offset=420, length=45),
                                          MessageEntityBold(offset=482, length=6),
                                          MessageEntityBold(offset=493, length=15),
                                          MessageEntityUrl(offset=606, length=34)], views=None, edit_date=None,
                                post_author=None, grouped_id=None), entity = User(id=93372553, is_self=False,
                                                                                  contact=False, mutual_contact=False,
                                                                                  deleted=False, bot=True,
                                                                                  bot_chat_history=False,
                                                                                  bot_nochats=True, verified=True,
                                                                                  restricted=False, min=False,
                                                                                  bot_inline_geo=False, support=False,
                                                                                  access_hash=-3190507674354563724,
                                                                                  first_name='BotFather',
                                                                                  last_name=None, username='BotFather',
                                                                                  phone=None, photo=UserProfilePhoto(
        photo_id=401032061935265706, photo_small=FileLocationToBeDeprecated(volume_id=802332692, local_id=16833),
        photo_big=FileLocationToBeDeprecated(volume_id=802332692, local_id=16835), dc_id=1), status=None,
                                                                                  bot_info_version=19,
                                                                                  restriction_reason=None,
                                                                                  bot_inline_placeholder=None,
                                                                                  lang_code=None)), total = 8]
